<style type="text/css">
    .gli {
    	color: dodgerblue;
        float: right;
        margin: 0 5px 0 5px;
        cursor: pointer;
    }
</style>
<form method="post" action="consultas">
	<input type="hidden" name="pac" id="pac">
	<input type="hidden" name="sub" id="sub">
</form>
<div class="contenedor">
	<div class="row">
		<div class="col-lg-12">
			<table class="table table-hover" id="tablaConsultas">
				<thead>
					<th>Fecha</th>
					<th>Paciente</th>
					<th>Motivo</th>
				</thead>
				<tbody>
					<?php foreach ($consultas as $con): ?>
						<tr class="fila">
							<td><?php echo date_format($con['FECHA_SUB'],'d/m/Y') ?></td>
							<td><?php echo $con['NOMBRE'].' '.$con['APELLIDO_PATERNO'].' '.$con['APELLIDO_MATERNO'] ?></td>
							<td><?php echo $con['MOTIVO_CONS'] ?><i class="gli fa fa-stethoscope" onclick="irconsulta('<?php echo $con['IDPAC'] ?>','<?php echo $con['IDSUB'] ?>')"></i></td>
						</tr>
					<?php endforeach ?>

				</tbody>
			</table>
		</div>	
	</div>
</div>
<script type="text/javascript">
	$("#tablaConsultas").dataTable();
	function irconsulta (idPac, idSub) {
		
	}
</script>
