<?php 
    $form->setAttribute('action', $this->url('pacientes', array('action'=>'nuevocliente')))
     ->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
		  <div class="row">
            <div id="divReceptor" class="form-group col-lg-3">
               <?php
                   $element = $form->get('RFC');
                   echo $this->formRow($element);
               ?>
            </div>
                <div id="divReceptor" class="form-group col-lg-5" >
                   <?php
                       $element = $form->get('NOMBRE');
                       echo $this->formRow($element);
                   ?>  
               </div>
          </div>
          <div class="row">
          	    <div id="divReceptor" class="form-group col-lg-3" >
          	       <?php
          	           $element = $form->get('PAIS');
          	           echo $this->formRow($element);
          	       ?>  
          		</div>

          	    <div id="divReceptor" class="form-group col-lg-3" >
          	       <?php
          	           $element = $form->get('ESTADO');
          	           echo $this->formRow($element);
          	       ?>  
          	   </div>
          	
          	    <div id="divReceptor" class="form-group col-lg-3" >
          	       <?php
          	           $element = $form->get('MUNICIPIO');
          	           echo $this->formRow($element);
          	       ?>  
          	   </div>
          </div>
        <div class="row"> 
          	<div id="divReceptor" class="form-group col-lg-3" >
	   		    <?php
	   		        $element = $form->get('CALLE');
	   		        echo $this->formRow($element);
	   		    ?>  
	   		</div>
                
            <div id="divReceptor" class="form-group col-lg-2" >
               <?php
                   $element = $form->get('NUM_INT');
                   echo $this->formRow($element);
               ?>  
           </div>

            <div id="divReceptor" class="form-group col-lg-2" >
               <?php
                   $element = $form->get('NUM_EXT');
                   echo $this->formRow($element);
               ?>  
           </div>
            <div id="divReceptor" class="form-group col-lg-3" >
               <?php
                   $element = $form->get('COLONIA');
                   echo $this->formRow($element);
               ?>  
           </div>
           <div id="divReceptor" class="form-group col-lg-2" >
               <?php
                   $element = $form->get('CP');
                   echo $this->formRow($element);
               ?>  
           </div>
        </div>
        	<div class="row">
        		 <div id="divReceptor" class="form-group col-lg-3" >
        		    <?php
        		        $element = $form->get('EMAIL');
        		        echo $this->formRow($element);
        		    ?>  
        		</div>
        		
        		 <div id="divReceptor" class="form-group col-lg-3" >
        		    <?php
        		        $element = $form->get('TELEFONO');
        		        echo $this->formRow($element);
        		    ?>  
        		</div>

        		 <div id="divReceptor" class="form-group col-lg-3" >
        		    <?php
        		        $element = $form->get('TELMOVIL');
        		        echo $this->formRow($element);
        		    ?>  
        		</div>
        	</div>
      <div class="modal-footer">
        <button type="button" id="cGuardar" class="btn btn-primary" onclick="guardarCliente()">Guardar</button>
        <?php echo $this->form()->closeTag(); ?>	
      </div>
<script type="text/javascript">
  $( document ).ready(function() {
    $("#sEstados").val(8);
    $("#sPaises").val(146);
    $('#sEstados').chosen({width: "95%"});
    $('#sMunicipios').chosen({width: "95%"});
    
    municipios2(8);
  });
  function guardarCliente() {
    $.ajax({
            type: "POST",
            data: $('#receptor').serialize(),
            url: "nuevocliente",
            dataType: "json",
            success: function(data) {
               if(data.result == 1){
                $('#modal-body').prepend('<div class="alert alert-success" role="alert">Cliente agregado exitosamente</div>'); 
                $('#cGuardar').prop("disabled",true);
                clientes(data.cliente);
               } else if (data.result == 0) {
                $('#modal-body').prepend('<div class="alert alert-danger" role="alert">La solicitud no se pudo completar. Mensajes : '+data.mensajes+ '</div>');
                $('#cGuardar').prop("disabled",true);
               }
               else {
                $('#modal-body').prepend('<div class="alert alert-danger" role="alert">Algo anda muy mal</div>');
               }
                
            },
            error: function(){
                 $('#modal-body').prepend('<div class="alert alert-danger" role="alert">Solicitud incompleta.</div>');
            }
      });
  }
</script>