<div class="col-1g-12" style="margin-bottom:25px">
	<button type="button" class="btn btn-primary" onclick="materialModal()">Añadir material</button>
</div>
<div class="contenedor">
  <div class="row">
    <div class="col-lg-12" id="divTablaInventario">
      
    </div>
  </div>
</div>
<div class="modal fade" id="modalMaterialNuevo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
        <h4 class="modal-title" id="modalLabel">Agregar material</h4>
      </div>
      <div class="modal-body" id="modalMaterialNuevoBody" style="min-height:150px">
        
      </div>
      <div class="modal-footer" id="modalMaterialNuevoFooter">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary" id="bEnviar" onclick="guardarMaterial()">Guardar</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
	    listaInventario();
	});
	function materialModal() {
		$('#modalMaterialNuevo').modal('show');
		$.ajax({
            type: "GET",
            url: "materialnuevo",
            dataType: "html",
            success: function(data) {
               $('#modalMaterialNuevoBody').html(data);
            },
            error: function(){
                  alert('Ocurrió un error, inténtelo más tarde.');
            }
    	});
	}
	function listaInventario() {	
		$.ajax({
            type: "GET",
            url: "listamaterial",
            dataType: "html",
            success: function(data) {
               $("#divTablaInventario").html(data);
            },
            error: function(){
                  alert('Ocurrió un error, inténtelo más tarde.');
            }
    	});
	}
</script>