<?php 
	$form->setAttribute('action', $this->url('inventario', array('action'=>'materialnuevo')))
     ->prepare();
     $form->get('CANTIDADMIN')->setAttribute('style','width:50%');
     $form->get('CANTIDAD')->setAttribute('style','width:50%');
     $form->get('CANTIDADMIN')->setAttribute('data-trigger','focus');
     echo $this->headScript()
            ->appendFile($this->basePath() . '/public/js/recursos/verificarCampos.js');

     echo $this->headScript()
            ->appendFile($this->basePath() . '/public/js/transition.js');

?>
<div class="col-sm-12" style="float:none">
	<?php echo $this->form()->openTag($form); ?>
	<?php echo $this->formRow($form->get('ID')); ?>
	<div class="col-sm-12" style="float:none">
		<?php echo $this->formRow($form->get('MATERIAL')); ?>
	</div>
	<div class="col-sm-6" style="float:none">
		<?php echo $this->formRow($form->get('FECHACADUCIDAD')); ?>
	</div>
	<div class="col-sm-12" style="float:none">
		<?php echo $this->formRow($form->get('CANTIDAD')); ?>
	</div>
	<div class="col-sm-12" style="float:none">
		<?php echo $this->formRow($form->get('CANTIDADMIN')); ?>
	</div>
	
	<?php echo $this->form()->closeTag(); ?>
</div>

<script type="text/javascript">
$(function() {
	$('[data-placement="right"]').popover();
});


	function guardarMaterial () {
		$.ajax({
            type: "POST",
            url: "materialnuevo",
            dataType: "json",
            data: $("#inventario").serialize(),
            success: function(data) {
				$('#modalMaterialNuevoBody').prepend('<div class="alert alert-success fade" id="alertMaterialCreado" role="alert" style="padding:5px">Material agregado</div>');
				$('#alertMaterialCreado').transition({ opacity: 1 });
				listaInventario();
            },
            error: function(){
                $('#modalMaterialNuevoBody').prepend('<div class="alert alert-danger fade" id="alertMaterialCreado" role="alert" style="padding:5px">El material no pudo ser agregado, existe un problema de red.</div>');
				$('#alertMaterialCreado').transition({ opacity: 1 });
            }
    	});
	}
</script>
