<div class="col-1g-12" style="margin-bottom:25px">
	<button type="button" class="btn btn-primary" onclick="agregarfila()">Nueva Dependencia</button>
</div>
<div class="contenedor">
  <div class="row">
    <div class="col-lg-12" id="divTablaDependencia">
      
    </div>
  </div>
</div>
<div class="modal fade" id="modalDependenciaNueva" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
        <h4 class="modal-title" id="modalLabel">Agregar dependencia</h4>
      </div>
      <div class="modal-body" id="modalDependenciaNuevaBody" style="min-height:150px">
        
      </div>
      <div class="modal-footer" id="modaldependenciaNuevoFooter">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary" id="bEnviar" onclick="guardardependencia()">Guardar</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
	    listaDependencia();
	});
	function dependenciaModal() {
		$('#modalDependenciaNueva').modal('show');
		$.ajax({
            type: "GET",
            url: "dependencianuevo",
            dataType: "html",
            success: function(data) {
               $('#modalDependenciaNuevaBody').html(data);
            },
            error: function(){
                  alert('Ocurrió un error, inténtelo más tarde.');
            }
    	});
	}
	function listaDependencia() {	
		$.ajax({
            type: "GET",
            url: "<?php echo $this->basePath() ?>/dependencias/listadependencias",
            dataType: "html",
            success: function(data) {
               $("#divTablaDependencia").html(data);
            },
            error: function(){
                  alert('Ocurrió un error, inténtelo más tarde.');
            }
    	});
	}
</script>