<?php header("Content-Type: text/html;charset=utf-8"); 
setlocale(LC_ALL,"es_ES");

?>
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Start Bootstrap - SB Admin Version 2.0 Demo</title>

    <!-- Core CSS - Include with every page -->
    <link href="<?php echo $this->basePath() ?>/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo $this->basePath() ?>/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="<?php echo $this->basePath() ?>/js/chosen_v1.1.0/chosen.css" rel="stylesheet">
    <link href="<?php echo $this->basePath() ?>/js/fullcalendar-2.0.2/lib/jquery-ui.css" rel="stylesheet">
    <link href="<?php echo $this->basePath() ?>/js/fullcalendar-2.0.2/lib/jquery-ui.theme.css" rel="stylesheet">
    <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/style.css')
                                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css'); ?>
    <!-- Page-Level Plugin CSS - Blank -->

    <!-- SB Admin CSS - Include with every page -->
    <link href="<?php echo $this->basePath() ?>/css/sb-admin.css" rel="stylesheet">
    <link href="<?php echo $this->basePath() ?>/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
</head>

<body>

    <div id="wrapper">

        <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Expediente Electrónico Admin.</a>
                
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <!-- /.dropdown-messages -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <!-- /.dropdown-tasks -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <!-- /.dropdown-alerts -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> Perfil de Usuario</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Opciones</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="/csnusertest/html/user/logout"><i class="fa fa-sign-out fa-fw"></i> Cerrar sesión</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

         
            <!-- /.navbar-static-side -->
        </nav>
        <script src="<?php echo $this->basePath() ?>/js/fullcalendar-2.0.2/lib/external/jquery/jquery.js"></script>
        <script src="<?php echo $this->basePath() ?>/js/fullcalendar-2.0.2/lib/jquery-ui.min.js"></script>
        <script src="<?php echo $this->basePath() ?>/js/bootstrap.min.js"></script>
        <script src="<?php echo $this->basePath() ?>/js/plugins/metisMenu/jquery.metisMenu.js"></script>

        <!-- Page-Level Plugin Scripts - Blank -->

        <!-- SB Admin Scripts - Include with every page -->
        <script src="<?php echo $this->basePath() ?>/js/sb-admin.js"></script>

        <!-- Page-Level Demo Scripts - Blank - Use for reference -->
        <script src="<?php echo $this->basePath() ?>/js/plugins/dataTables/jquery.dataTables.js"></script>
        <script src="<?php echo $this->basePath() ?>/js/plugins/dataTables/dataTables.bootstrap.js"></script>
        <script src="<?php echo $this->basePath() ?>/js/chosen_v1.1.0/chosen.jquery.js"></script>
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <?php echo $this->content; ?>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->

    <!-- Core Scripts - Include with every page -->
    
</body>

</html>
