<?php 
  $ruta = 'http://localhost/imedich/';
?>
<style type="text/css">
	@page {
            margin-top: 1.5em;
            margin-left: 0.6em;
            margin-bottom: 0.6em;
            margin-right: 0.6em;
            font-size: 14px;
        }
    html {
      font-family: sans-serif;
      -webkit-text-size-adjust: 100%;
          -ms-text-size-adjust: 100%;
    }
    hr {
      height: 0;
      -webkit-box-sizing: content-box;
         -moz-box-sizing: content-box;
              box-sizing: content-box;
    }
    .spaninfo {
      color: #fff;
      position: absolute;
      top: 100px;
      left: 10px;
      width: 87%;
    }
    h1,
    h2,
    h3,
    h4,
    h5,
    h6,
    .h1,
    .h2,
    .h3,
    .h4,
    .h5,
    .h6 {
      font-family: inherit;
      font-weight: 500;
      line-height: 1.1;
      color: inherit;
    }
    h1,
    .h1 {
      font-size: 36px;
    }
    h2,
    .h2 {
      font-size: 30px;
    }
    h3,
    .h3 {
      font-size: 24px;
    }
    h4,
    .h4 {
      font-size: 18px;
    }
    h5,
    .h5 {
      font-size: 14px;
    }
    h6,
    .h6 {
      font-size: 12px;
    }
    p {
      margin: 0 0 10px;
    }
    .imagen {
     
    }
</style>
<body>
	<div>
		<table cellspacing="5px" width="100%">
			<tbody>
				<tr>
					<td width="170px" style="vertical-align:text-top">
						<div style="margin-bottom:5px">
              <span class="spaninfo">
                <?php echo 'Fecha:<br>'.date_format($fecha,'d/m/Y').'<br><br>Paciente:<br>'.$paciente.'<br><br>Doctor intérprete:<br>'.$doctor; ?>
              </span>
              <img width="150px" src="<?php echo $ruta ?>/public/imagenes/Side_bar.png">
            </div>
						<?php foreach ($imagenes as $ima) { ?>
              <div style="margin-bottom:5px"><img width="150px" src="<?php echo $ruta ?>/public/imagenes/Estudios/<?php echo $idEstudio.'/'.$ima['IMAGEN']?>"></div>
              <?php } ?>
					</td>
					<td style="vertical-align:text-top">
						<div><img src="<?php echo $ruta ?>/public/imagenes/Logo_Imedich.png"></div>
						<hr style="color:dodgerblue">
            <h3>Resultados de los estudios: <?php foreach ($categorias as $cat){echo $cat['NOMBRECATEGORIA'].', ';}   ?>
              
            </h3>
						<p><?php echo nl2br($interpretacion) ?></p>
											
					</td>
				</tr>
			</tbody>
		</table>
    <?php $x = count($imagenes); ?>

    <?php $x=0; foreach ($imagenes as $img) { $x++; if($x%2!=0) { ?>
      <table cellspacing="5px">
        <tbody>
          <tr>
            <td width="170px" style="vertical-align:text-top">
              <div style="margin-bottom:5px"><img width="150px" src="<?php echo $ruta ?>/public/imagenes/Side_bar.png"></div>
              <?php foreach ($imagenes as $ima) { ?>
              <div style="margin-bottom:5px"><img width="150px" src="<?php echo $ruta ?>/public/imagenes/Estudios/<?php echo $idEstudio.'/'.$ima['IMAGEN']?>"></div>
              <?php } ?>
            </td>
            <td style="vertical-align:text-top">
              <div><img src="<?php echo $ruta ?>/public/imagenes/Logo_Imedich.png"></div>
              <hr style="color:dodgerblue">
              <?php } ?>
              <div style="margin-bottom: 25px">
                <img class="imagen" width="580px" height="400px" src="<?php echo $ruta ?>/public/imagenes/Estudios/<?php echo $idEstudio.'/'.$img['IMAGEN']?>">    
              </div>
              <?php if($x%2==0) { ?>   
            </td>
          </tr>
        </tbody>
      </table>
    <?php }} ?>
	</div>
</body>
</html>
