<?php 
  $ruta = 'http://localhost/imedich/';
?>
<style type="text/css">
  .page {
  page-break-after:always;
  position: relative;
  }
</style>
<div style="position: fixed;bottom: 80px; left: 10px; "><img width="180px" height="80px" src="<?php echo $ruta ?>/public/imagenes/Logo-Medimagen.png"></div>
<div><img width="180px" height="80px" src="<?php echo $ruta ?>/public/imagenes/Logo-Medimagen.png"></div>
<hr style="color:red">
<h3>Interpretación de los estudios: </h3>
<div class="page">
<!-- content of page -->

<?php echo nl2br($interpretacion) ?>

