<?php setlocale(LC_MONETARY, 'es_MX'); ?>
<style type="text/css">
	.seleccionado {
		background-color: dodgerblue;
	}
	.col-sm-6 {
		width: auto;
	}
</style>
<div class="col-lg-12">
	<table class="table" id="tablaCategorias">
		<thead>
			<th>Nombre</th>
			<th>Costo para:</th>
			<th>Costo</th>
			<th>Costo + IVA</th>
		</thead>
		<tbody>
			<?php foreach ($categorias as $categoria) { $costo = $categoria[0]['COSTO']; $costoiva = $costo*1.16; ?>
				<tr idmaterial="<?php echo $categoria['ID'] ?>">
					<td>
					<?php if($categoria[0]['ACTIVO'] == 1) 
						{ echo '<font color="blue">'.$categoria[0]['NOMBRECATEGORIA'].'</font>';} else {
						  echo '<font color="red">'.$categoria[0]['NOMBRECATEGORIA'].'</font>';	
						}
					 ?></td>
					<td><?php echo $categoria['NOMBREDEPENDENCIA'] ?></td>
					<td><?php echo '$ '.number_format($costo,2); ?></td>
					<td><?php echo '$ '.number_format($costoiva,2); ?><span class="glyphicon glyphicon-pencil" style="float:right;cursor:pointer;color:dodgerblue" onclick="categoriaModalEditar(<?php echo $categoria[0]['ID'] ?>)"></span></td>
				</tr>
			<?php } ?>
		</tbody>
	</table>	
</div>
<script type="text/javascript">
	$(document).ready(function() {
	    $('#tablaCategorias').dataTable();
	});
	
</script>
