<style type="text/css">
	.ui-autocomplete {
		z-index: 1051;
	}
</style>
<div class="alert alert-success fade" id="alertEstudioCreado1" role="alert" style="padding:5px;display:none">Estudio agregado</div>
<div class="alert alert-danger fade" id="alertEstudioCreado2" role="alert" style="padding:5px;display:none">El estudio no pudo ser agregado, existe un problema de red.</div
<div style="float:none;margin-bottom:10px">
	<?php echo $this->form()->openTag($form); ?>
	<?php echo $this->formRow($form->get('ID')); ?>
	<div class="row">
    <div class="col-sm-5">
      <?php echo $this->formRow($form->get('FECHA')); ?>
    </div> 
  </div>
  <div class="row">
      <div class="col-sm-8">
        <label>Buscar paciente:</label>
        <input type="text" id="selectPaciente" class="form-control" style="margin-bottom:10px">
        <label>Paciente:</label>
        <span>
          <?php if ($nompaciente) { ?>
            <font color="green" id="spanPaciente"><?php echo $nompaciente; ?></font>  
          <?php } else { ?>
            <font color="green" id="spanPaciente"></font>
          <?php } ?>
        </span>
        <?php echo $this->formRow($form->get('PACIENTE')); ?>
      </div>
  </div>
  <div style="margin-bottom:10px">
    <?php echo $this->formRow($form->get('DEPENDENCIA')); ?>
  </div>

  <div class="col-sm-8" style="margin-bottom:10px">
    <?php echo $this->formRow($form->get('DOCTORENV')); ?>
  </div>
	<div class="col-sm-3" style="margin-bottom:10px">
		<button id="bNuevodoctor" type="button" class="btn btn-default" onclick="doctorModal()" style="margin-top:25px">Nuevo doctor</button>
	</div>
  <div class="col-sm-12">
    <label style="color:red" id="labelInt">Necesita int. :</label>
    <?php echo $this->formRow($form->get('REVISION')); ?>
  </div>
	<div>
		<?php echo $this->formRow($form->get('TIPOS[]')); ?>
	</div>
	<?php echo $this->form()->closeTag(); ?>
</div>
<script src="//cdnjs.cloudflare.com/ajax/libs/numeral.js/1.4.5/numeral.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
  $('#sDependencia').chosen();
	$('#sTipos').chosen();
	$('#sDoctor').chosen();
  var cambiarcsslabel = function() {
    if ($('#checkRevision').prop('checked')){
      $('#labelInt').css('color','');  
    } else {
      $('#labelInt').css('color','red');  
    }
  };
  $('#checkRevision').on('click', cambiarcsslabel);
	function split( val ) {
          return val.split( /;\s*/ );
        }
        function extractLast( term ) {
          return split( term ).pop();
        }
        $( "#selectPaciente" )
      // don't navigate away from the field on tab when selecting an item
      .bind( "keydown", function( event ) {
        if ( event.keyCode === $.ui.keyCode.TAB &&
            $( this ).autocomplete( "instance" ).menu.active ) {
          event.preventDefault();
        }
      })
      .autocomplete({
        source: function( request, response ) {
          $.getJSON( "pacientes", {
            term: extractLast( request.term )
          }, response );
        },
        search: function() {
          // custom minLength
          var term = extractLast( this.value );
          if ( term.length < 2 ) {
            return false;
          }
        },
        focus: function() {
          // prevent value inserted on focus
          return false;
        },
        select: function( event, ui ) {
          $("#cIdPaciente").val(ui.item.id);
          $("#spanPaciente").text(ui.item.value);
          var terms = split( this.value );
          // remove the current input
          terms.pop();
          // add the selected item
          terms.push( ui.item.value );
          // add placeholder to get the comma-and-space at the end
          terms.push( "" );
          this.value = "";
          return false;
        }
      }); 
});
  
  var cambiartipos = function() {
    tiposx(this.value);
  };
  
  $('#sDependencia').on('change',cambiartipos);

  function tiposx (id) {
    $('#sTipos').empty();
    $.post("<?php echo $this->basePath() ?>/dependencias/gettipos", {dependencia: id},
          function (data) {
           for(i = 0; i < data.length; i++){
            costo = (data[i].COSTO*1.16);
            $('#sTipos').append("<option value='"+data[i].ID+"'>"+data[i].NOMBRECATEGORIA+" ("+numeral(costo).format('$ 0,0.00')+")</option>");
          }
          $('#sTipos').trigger('chosen:updated');
          });
  }

	function guardarEstudio () {
    if($("#cIdPaciente").val() != '' && $("#sDoctor").val() != '' && $('#cFecha').val() != ''){
          $.ajax({
                  type: "POST",
                  url: "nuevoestudio",
                  dataType: "json",
                  data: $("#estudios").serialize(),
                  success: function(data) {
              $('#alertEstudioCreado1').css('display','block').transition({ opacity: 1 });
              listaEstudios();
              $('#modalEstudioNuevo').delay(2000).modal('hide');
                  },
                  error: function(){
              $('#alertEstudioCreado2').css('display','block').transition({ opacity: 1 });
                  }
            });
        } else {
          alert('Se necesita un paciente y un doctor registrados o la fecha esta vacía.'); 
        }
		
	}

</script>
